# /// script
# requires-python = ">=3.11"
# dependencies = [
#     "indipyserver"
# ]
# ///

"""Set to connect to remote servers led1.py, led2.py and sendblob.py
   Rather than using remote machines, these three services are all on
   one machine using different ports"""


import asyncio
from indipyserver import IPyServer, version


if __name__ == "__main__":

    server = IPyServer(host="localhost", port=7624, maxconnections=5)

    # connect to remote servers, note blob enabled on all links
    # so a client connected to any server can receive blobs, even though
    # they are only generated by the 7627 connection
    server.add_remote(host="localhost", port=7625, blob_enable=True)
    server.add_remote(host="localhost", port=7626, blob_enable=True)
    server.add_remote(host="localhost", port=7627, blob_enable=True)
    # Note blobs are enabled on the link to sendblob.py
    print(f"Running {__file__} with indipyserver version {version}")
    asyncio.run(server.asyncrun())
